# Generated by Django 3.0.6 on 2020-08-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='spacesAvailable',
            new_name='spaces',
        ),
        migrations.AlterField(
            model_name='event',
            name='spacesRemaining',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
