# Generated by Django 3.0.6 on 2020-08-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200822_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='spacesRemaining',
        ),
    ]
