# Generated by Django 3.0.6 on 2020-08-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_spacesremaining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventDateTime',
            new_name='startDateTime',
        ),
    ]
