# Generated by Django 3.0.6 on 2020-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200823_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='multiday',
            field=models.BooleanField(default=False),
        ),
    ]
