# Generated by Django 3.0.6 on 2020-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200823_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDateTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
