# Generated by Django 3.0.6 on 2020-08-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200823_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='spaces',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
