# Generated by Django 3.0.6 on 2020-08-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200823_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
