# Generated by Django 3.0.6 on 2020-08-24 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_auto_20200823_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='usersList',
        ),
        migrations.AddField(
            model_name='event',
            name='signupClose',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='signupPublish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='signupEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='signups',
            field=models.ManyToManyField(blank=True, to='events.signupEntry'),
        ),
    ]
