# Generated by Django 3.0.6 on 2020-08-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200824_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endDate',
        ),
        migrations.AddField(
            model_name='event',
            name='endDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
