# Generated by Django 3.0.6 on 2020-08-24 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_auto_20200824_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='weekendSignupEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowBoard', models.CharField(choices=[('None', 'None'), ('Foamie', 'Foamie (Beginner Board)'), ('Bic', 'Bic (Hard Intermediate Board)'), ('Foamie Shortboard', 'Foamie Shortboard (Intermediates)'), ('Shortboard', 'Shortboard')], default='None', max_length=20)),
                ('bringBoard', models.CharField(choices=[('None', 'None'), ('Long', 'Board over 8ft'), ('Medium', 'Board between 6ft6 and 7ft6'), ('Short', 'Board under 6ft6')], default='None', max_length=20)),
                ('wetsuit', models.CharField(choices=[('None', "I'll bring my own"), ('w-6', 'Womens 6'), ('w-8', 'Womens 8'), ('w-10', 'Womens 10'), ('w-12', 'Womens 12'), ('w-14', 'Womens 14'), ('w-16', 'Womens 16'), ('m-S', 'Mens Small'), ('m-M', 'Mens Medium'), ('m-L', 'Mens Large'), ('m-XL', 'Mens Extra Large')], default='None', max_length=20)),
                ('driveCar', models.BooleanField(default=False)),
                ('roofRacks', models.BooleanField(default=False)),
                ('carSeats', models.IntegerField(blank=True)),
                ('driveMinibus', models.BooleanField(default=False)),
                ('endQuestionAnswer', models.TextField()),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='multiday',
        ),
        migrations.RemoveField(
            model_name='event',
            name='signups',
        ),
        migrations.AddField(
            model_name='event',
            name='endQuestion',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='signupEntry',
        ),
        migrations.AddField(
            model_name='event',
            name='weekendSignups',
            field=models.ManyToManyField(blank=True, to='events.weekendSignupEntry'),
        ),
    ]
