# Generated by Django 3.0.6 on 2020-08-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200824_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendsignupentry',
            name='carSeats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weekendsignupentry',
            name='roofRacks',
            field=models.CharField(choices=[('No', 'No'), ('I have a hard roofrack', 'I have a hard roofrack'), ('I can put a club soft roof rack on', 'I can put a club soft roof rack on')], default="Can't use a roofrack", max_length=100),
        ),
    ]
