# Generated by Django 3.0.6 on 2020-08-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20200826_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendsignupentry',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
