# Generated by Django 3.0.6 on 2020-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20200827_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendsignupentry',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
