# Generated by Django 3.0.6 on 2020-08-30 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0022_auto_20200827_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekendsignupentry',
            name='user',
        ),
        migrations.AddField(
            model_name='weekendsignupentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
