# Generated by Django 3.0.6 on 2020-09-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0023_auto_20200830_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='camping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='lessonsAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='rentalAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weekendsignupentry',
            name='tent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='weekendSignups',
            field=models.ManyToManyField(blank=True, null=True, to='events.weekendSignupEntry'),
        ),
        migrations.AlterField(
            model_name='weekendsignupentry',
            name='endQuestionAnswer',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='abroadSignupEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('rental', models.BooleanField(default=False)),
                ('lessons', models.BooleanField(default=False)),
                ('endQuestionAnswer', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='abroadSignups',
            field=models.ManyToManyField(blank=True, null=True, to='events.abroadSignupEntry'),
        ),
    ]
