# Generated by Django 3.0.6 on 2020-09-03 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0024_auto_20200901_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='abroadSignups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='camping',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lessonsAvailable',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rentalAvailable',
        ),
        migrations.RemoveField(
            model_name='weekendsignupentry',
            name='tent',
        ),
        migrations.RemoveField(
            model_name='weekendsignupentry',
            name='user',
        ),
        migrations.AddField(
            model_name='weekendsignupentry',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='abroadSignupEntry',
        ),
    ]
