# Generated by Django 3.0.6 on 2020-09-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20200903_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnersignupentry',
            name='borrowBoard',
            field=models.CharField(choices=[('None', 'None'), ('Foamie', 'Foamie (Beginner Board)'), ('Bic', 'Bic (Hard Intermediate Board)'), ('Foamie Shortboard', 'Foamie Shortboard (Intermediates)'), ('Shortboard', 'Shortboard')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='beginnersignupentry',
            name='carSeats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beginnersignupentry',
            name='driveCar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beginnersignupentry',
            name='roofRacks',
            field=models.CharField(choices=[('No', 'No'), ('I have a hard roofrack', 'I have a hard roofrack'), ('I can put a club soft roof rack on', 'I can put a club soft roof rack on')], default="Can't use a roofrack", max_length=100),
        ),
        migrations.AddField(
            model_name='beginnersignupentry',
            name='wetsuit',
            field=models.CharField(choices=[('None', "I'll bring my own"), ('w-6', 'Womens 6'), ('w-8', 'Womens 8'), ('w-10', 'Womens 10'), ('w-12', 'Womens 12'), ('w-14', 'Womens 14'), ('w-16', 'Womens 16'), ('m-S', 'Mens Small'), ('m-M', 'Mens Medium'), ('m-L', 'Mens Large'), ('m-XL', 'Mens Extra Large')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='beginnerSignups',
            field=models.ManyToManyField(blank=True, to='events.beginnerSignupEntry'),
        ),
        migrations.AlterField(
            model_name='event',
            name='abroadSignups',
            field=models.ManyToManyField(blank=True, to='events.abroadSignupEntry'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Weekend Trip', 'Weekend Trip'), ('Abroad Trip', 'Abroad Trip'), ('Beginner Session', 'Beginner Session'), ('Social', 'Social'), ('Misc.', 'Misc.')], default='Misc.', max_length=30, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='weekendSignups',
            field=models.ManyToManyField(blank=True, to='events.weekendSignupEntry'),
        ),
    ]
