# Generated by Django 3.0.6 on 2020-09-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20200903_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='camping',
            field=models.BooleanField(default=False, help_text='Is it a camping trip?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDateTime',
            field=models.DateTimeField(blank=True, help_text='When the event end (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='endQuestion',
            field=models.TextField(blank=True, help_text='Fun question for the end of signup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lessonsAvailable',
            field=models.BooleanField(default=False, help_text='Are lessons available?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publishDateTime',
            field=models.DateTimeField(help_text='When the event will appear on the events page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rentalAvailable',
            field=models.BooleanField(default=False, help_text='Is board rental available?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='signupClose',
            field=models.DateTimeField(blank=True, help_text='When the signup will dissapear', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='signupPublish',
            field=models.DateTimeField(blank=True, help_text='When the signup appears on the event page', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='signupRequired',
            field=models.BooleanField(default=False, help_text='Is a signup is required? (For weekend, abroad, and beginner trips)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='spaces',
            field=models.IntegerField(blank=True, help_text='Spaces on the trip', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDateTime',
            field=models.DateTimeField(help_text='When the event starts'),
        ),
    ]
