# Generated by Django 3.0.6 on 2020-09-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20200903_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDateTime',
            field=models.DateTimeField(blank=True, help_text='When the event ends (optional)', null=True),
        ),
    ]
