# Generated by Django 3.0.6 on 2020-09-07 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20200903_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the event ends (optional)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='rentalAvailable',
            field=models.BooleanField(default=False, help_text='Is equipment rental available?'),
        ),
    ]
