# Generated by Django 3.1.1 on 2020-10-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20200907_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnersignupentry',
            name='endQuestionAnswer',
            field=models.TextField(blank=True),
        ),
    ]
