# Generated by Django 3.1.1 on 2020-10-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20201025_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abroadsignupentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='beginnersignupentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weekendsignupentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
