# Generated by Django 3.1.1 on 2020-10-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots',
            name='page',
        ),
    ]
