# Generated by Django 3.1.1 on 2020-10-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_spots_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='distance',
            field=models.IntegerField(default='distance away in miles (by gmaps)'),
        ),
    ]
