# Generated by Django 3.1.1 on 2020-10-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('text1', models.TextField()),
                ('pic1', models.ImageField(blank=True, upload_to='blog/')),
                ('text2', models.TextField(blank=True)),
                ('pic2', models.ImageField(blank=True, upload_to='blog/')),
                ('text3', models.TextField(blank=True)),
                ('pic3', models.ImageField(blank=True, upload_to='blog/')),
                ('text4', models.TextField(blank=True)),
                ('pic4', models.ImageField(blank=True, upload_to='blog/')),
                ('text5', models.TextField(blank=True)),
                ('pic5', models.ImageField(blank=True, upload_to='blog/')),
            ],
        ),
    ]
