# Generated by Django 3.1.1 on 2020-12-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0003_surfboard_watertight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wetsuit',
            name='size',
            field=models.CharField(choices=[('Childs age 16', 'Childs age 16'), ('Womens 6', 'Womens 6'), ('Womens 8', 'Womens 8'), ('Womens 10', 'Womens 10'), ('Womens 12', 'Womens 12'), ('Womens 14', 'Womens 14'), ('Womens 16', 'Womens 16'), ('Mens Small', 'Mens Small'), ('Mens Medium', 'Mens Medium'), ('Mens Large', 'Mens Large'), ('Mens Extra Large', 'Mens Extra Large')], max_length=30),
        ),
        migrations.AlterField(
            model_name='wetsuit',
            name='thickness',
            field=models.CharField(choices=[('5/4/3mm', '5/4/3mm'), ('5/4mm', '5/4mm'), ('5/3mm', '5/3mm'), ('4/3mm', '4/3mm'), ('3/2mm', '3/2mm')], max_length=10),
        ),
    ]
